# Generated by Django 3.0.3 on 2020-02-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
